- hosts: windows_server

  tasks:
    - name: Install atom from Choco
      win_chocolatey:
        name: atom
        state: present
        
    - name: Reboot VM
      win_reboot:

    - name: Wait default 120 seconds for port 3389 to become open, don't start checking for 15 seconds
      win_wait_for:
        port: 3389
    
