- hosts: all
  become: true
  roles:
    - role: geerlingguy.ntp
      vars:
        ntp_timezone: Europe/Warsaw
        ntp_manage_config: true
        ntp_servers:
          - "custom.corp.com iburst"